### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by duesee** [duesee/abnf#8]
* [ ] Nom Error Handling (where and why does the parser failed?)
* [ ] Define the public interface (see [Rust API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/about.html))
  * [ ] remove `Box`es
  * [ ] make fields private
  * [ ] "lock" `enum Definition`?
* [x] Solve #5 (return e.g. Result<Vec<Rule>, abnf::Error>)
* [x] Solve #6 (implement incremental alternatives)
* [ ] Solve #7 (will change parse functions behaviour)
* [x] Documentation
* [ ] Release 1.0 :-)
